const express=require("express");
const router=express.Router();
const {verifyToken}=require("../middleware/auth-middleware");
const c=require("../controllers/storage-controller");
router.use(verifyToken);
router.get("/files",c.list);
router.patch("/files/:id",c.patchFile);
router.delete("/files/:id",c.trash);
router.post("/files/:id/restore",c.restore);
router.delete("/files/:id/permanent",c.permanent);
router.get("/folders",c.folders);
router.post("/folders",c.createFolder);
router.get("/stats",c.stats);
module.exports=router;