"use strict";

const axios = require("axios");

/**
 * Authentic, vetted interview questions compiled from authoritative sources:
 * - Cracking the Coding Interview (6th Edition) by Gayle Laakmann McDowell
 * - Operating System Concepts (Silberschatz, Galvin, Gagne)
 * - Database Management Systems (Ramakrishnan & Gehrke)
 * - Computer Networking: A Top-Down Approach (Kurose & Ross)
 * - Designing Data-Intensive Applications (Martin Kleppmann)
 * - Amazon Leadership Principles & Google Hiring Guidelines
 * - Top Interview 150 & Blind 75 / NeetCode 150
 */
const VETTED_INTERVIEW_QUESTIONS = [
  // ==========================================
  // CRACKING THE CODING INTERVIEW (CTCI) - DATA STRUCTURES
  // ==========================================
  {
    question: "CTCI 1.1: Implement an algorithm to determine if a string has all unique characters. What if you cannot use additional data structures?",
    answer: "Using an ASCII boolean vector or bit vector provides O(N) time and O(1) space. Without additional structures: compare every character to every other character in O(N^2) time, or sort the string in O(N log N) time and check neighboring characters.",
    explanation: "Ask the interviewer if the string is ASCII (128 alphabet) or Unicode. If length exceeds 128, immediately return false (Pigeonhole Principle). A 32-bit integer can act as a bit vector for lowercase [a-z], testing each character using bitwise shift: (checker & (1 << val)) > 0.",
    category: "Data Structures",
    topic: "Arrays & Strings",
    difficulty: "Easy",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 1.1)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    question: "CTCI 1.5: There are three types of edits on strings: insert a character, remove a character, or replace a character. Given two strings, write a function to check if they are one edit (or zero edits) away.",
    answer: "Check lengths first: if diff > 1, return false. Iterate through both strings with two pointers. On the first mismatch, if lengths are equal, advance both pointers (replacement check); if lengths differ, advance pointer in the longer string (insert/delete check). If a second mismatch occurs, return false.",
    explanation: "Time complexity is O(N) where N is the length of the shorter string. Space complexity is O(1). Merging replacement and insertion logic into a single loop avoids duplicate code.",
    category: "Data Structures",
    topic: "Arrays & Strings",
    difficulty: "Medium",
    company: "Microsoft",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 1.5)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/one-edit-distance/",
  },
  {
    question: "CTCI 1.7: Given an image represented by an NxN matrix, where each pixel is 4 bytes, write a method to rotate the image by 90 degrees clockwise in-place.",
    answer: "Rotate layer by layer from the outermost to the innermost. For each element at top[i], perform a 4-way circular swap: temp = top[i]; top[i] = left[i]; left[i] = bottom[i]; bottom[i] = right[i]; right[i] = temp.",
    explanation: "An alternative algebraic approach is to transpose the matrix (swap matrix[i][j] with matrix[j][i]) and then reflect/reverse each row horizontally. Both achieve O(N^2) time and O(1) auxiliary space in-place.",
    category: "Data Structures",
    topic: "Matrix Manipulation",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 1.7)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/rotate-image/",
  },
  {
    question: "CTCI 2.1: Write code to remove duplicates from an unsorted linked list. How would you solve it if a temporary buffer is not allowed?",
    answer: "With a buffer (HashSet): iterate through the linked list, track seen values in the set, delete any node whose value is already present in O(N) time and O(N) space. Without a buffer: use two pointers (current and runner) to check subsequent nodes, yielding O(N^2) time and O(1) space.",
    explanation: "Runner technique demonstrates space-time trade-offs. Point out that when garbage-collected languages (like Java/JS) delete a node (prev.next = current.next), the unreferenced node is reclaimed.",
    category: "Data Structures",
    topic: "Linked Lists",
    difficulty: "Easy",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 2.1)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/",
  },
  {
    question: "CTCI 2.8: Loop Detection — Given a circular linked list, implement an algorithm that returns the node at the beginning of the loop.",
    answer: "Use Floyd's Cycle-Finding Algorithm (Fast/Slow pointers). Fast moves 2 steps, Slow moves 1 step. When they collide inside the loop, reset Slow to the list Head while keeping Fast at the collision point. Move both at 1 step per iteration; their next meeting point is the exact loop entrance.",
    explanation: "Mathematical proof: Let k be the distance from head to loop start, and LOOP_SIZE be the loop length. When Slow enters the loop (after k steps), Fast is at (k % LOOP_SIZE). Fast catches Slow at LOOP_SIZE - (k % LOOP_SIZE) steps from the loop start. Resetting one pointer to Head and advancing both at speed 1 causes them to meet after exactly k steps at the loop entrance.",
    category: "Data Structures",
    topic: "Linked Lists",
    difficulty: "Medium",
    company: "Meta",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 2.8)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/linked-list-cycle-ii/",
  },
  {
    question: "CTCI 3.2: How would you design a stack which, in addition to push and pop, has a function min which returns the minimum element? push, pop and min should all operate in O(1) time.",
    answer: "Maintain an auxiliary stack (or keep a (value, currentMin) pair in each node). When pushing an element, push to minStack if it is <= current top of minStack. When popping, if the popped value equals minStack top, pop from minStack as well.",
    explanation: "Using an auxiliary stack only for elements that are <= current minimum avoids wasting memory when many large elements are pushed consecutively. Both time complexity O(1) and auxiliary space O(N) worst-case are achieved.",
    category: "Data Structures",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 3.2)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/min-stack/",
  },
  {
    question: "CTCI 3.4: Queue via Stacks — Implement a MyQueue class which implements a queue using two stacks.",
    answer: "Use stackNewest (for push operations) and stackOldest (for pop/peek operations). Enqueue pushes to stackNewest. Dequeue checks stackOldest: if empty, pop all elements from stackNewest and push them into stackOldest (reversing their order to FIFO), then pop from stackOldest.",
    explanation: "Amortized time complexity for pop/peek is O(1) because each element is moved between stacks exactly once in its lifetime, despite an occasional O(N) rebalancing step.",
    category: "Data Structures",
    topic: "Stacks & Queues",
    difficulty: "Easy",
    company: "Microsoft",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 3.4)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/implement-queue-using-stacks/",
  },
  {
    question: "CTCI 4.2: Minimal Tree — Given a sorted (increasing order) array with unique integer elements, write an algorithm to create a binary search tree with minimal height.",
    answer: "Find the middle element of the array and make it the root. Recursively construct the left subtree from the left subarray, and the right subtree from the right subarray.",
    explanation: "Base case: start > end returns null. Mid calculation: mid = start + (end - start) / 2 to avoid integer overflow. Time complexity is O(N) as each element is visited once; height is guaranteed to be ceil(log2(N)).",
    category: "Data Structures",
    topic: "Trees & Graphs",
    difficulty: "Easy",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 4.2)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
  },
  {
    question: "CTCI 4.5: Validate BST — Implement a function to check if a binary tree is a binary search tree.",
    answer: "Pass min and max bounds recursively down the tree: check(node, min, max). For current node, verify min < node.val <= max (depending on duplicate handling). Recursively call check(node.left, min, node.val) and check(node.right, node.val, max).",
    explanation: "A common pitfall is checking only that node.left.val < node.val < node.right.val, which misses violations in deeper descendant subtrees. Another valid approach is an in-order traversal verifying strictly increasing values, though the min/max range check is cleaner and requires O(log N) stack space.",
    category: "Data Structures",
    topic: "Trees & Graphs",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 4.5)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    question: "CTCI 4.7: Build Order — Given a list of projects and a list of dependencies, find a build order that allows projects to be built. If no valid build order exists, return an error.",
    answer: "Model projects as vertices and dependencies as directed edges in a Directed Acyclic Graph (DAG). Apply Kahn's Algorithm (Topological Sort via in-degrees) or DFS with cycle detection (3-state coloring: unvisited, visiting, visited). If a cycle exists, return an error.",
    explanation: "With Kahn's algorithm: compute in-degrees for all nodes. Enqueue all nodes with in-degree 0. While queue is not empty, dequeue a node, append it to build order, decrement in-degrees of its neighbors, and enqueue any neighbor whose in-degree hits 0. If build order length < total projects, a cyclic dependency exists. O(V + E) time.",
    category: "Algorithms",
    topic: "Graph Algorithms",
    difficulty: "Hard",
    company: "Apple",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 4.7)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/course-schedule-ii/",
  },

  // ==========================================
  // CTCI & ALGORITHMS - RECURSION & DYNAMIC PROGRAMMING
  // ==========================================
  {
    question: "CTCI 8.1: Triple Step — A child is running up a staircase with n steps and can hop either 1 step, 2 steps, or 3 steps at a time. Implement a method to count how many possible ways the child can run up the stairs.",
    answer: "Ways(n) = Ways(n-1) + Ways(n-2) + Ways(n-3). Base cases: Ways(0)=1, Ways(1)=1, Ways(2)=2. Compute iteratively using 3 state variables for O(N) time and O(1) space.",
    explanation: "Beware of integer overflow for n > 36; in practical coding rounds, use 64-bit integers or modulo arithmetic 10^9 + 7 as requested. Memoization or bottom-up tabulation transforms the naive O(3^N) recursive solution to O(N).",
    category: "Algorithms",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 8.1)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/climbing-stairs/",
  },
  {
    question: "CTCI 8.11: Coins — Given an infinite number of quarters (25 cents), dimes (10 cents), nickels (5 cents), and pennies (1 cent), write code to calculate the number of ways of representing n cents.",
    answer: "Unbounded knapsack DP. Let dp[i] be the number of ways to make amount i. Initialize dp[0] = 1. For each coin c in [25, 10, 5, 1], for i from c to n: dp[i] += dp[i - c]. Return dp[n].",
    explanation: "Iterating through coins in the outer loop ensures permutations like (10, 5) and (5, 10) are not double-counted as distinct combinations. Time complexity: O(coins * n), Space complexity: O(n).",
    category: "Algorithms",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "technical",
    source: "Cracking the Coding Interview (Ch 8.11)",
    sourceUrl: "https://www.crackingthecodinginterview.com/",
    problemUrl: "https://leetcode.com/problems/coin-change-ii/",
  },

  // ==========================================
  // OPERATING SYSTEMS (Silberschatz OS Concepts)
  // ==========================================
  {
    question: "Explain the four Coffman conditions for Deadlock and concrete techniques for Deadlock Prevention vs Avoidance (Banker's Algorithm).",
    answer: "Coffman conditions: 1) Mutual Exclusion, 2) Hold and Wait, 3) No Preemption, 4) Circular Wait. Prevention invalidates at least one condition (e.g. global linear resource ordering prevents circular wait). Avoidance dynamically checks safe states before allocating using Dijkstra's Banker's Algorithm.",
    explanation: "Banker's Algorithm uses Available[m], Max[n][m], Allocation[n][m], and Need[n][m] matrices. A state is safe if there exists a sequence <P1, P2, ..., Pn> of processes such that for each Pi, the resources that Pi can still request can be satisfied by currently available resources plus resources held by all Pj (j < i). Time complexity to evaluate safety is O(m * n^2).",
    category: "Operating Systems",
    topic: "Deadlocks & Resource Allocation",
    difficulty: "Hard",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Operating System Concepts (Silberschatz, Ch 8)",
    sourceUrl: "https://en.wikipedia.org/wiki/Banker%27s_algorithm",
  },
  {
    question: "What is Virtual Memory, how does the Page Fault handling mechanism work at the hardware/kernel boundary, and what causes Thrashing?",
    answer: "Virtual memory maps process address spaces to physical RAM via page tables and MMU. A page fault occurs when an invalid page table entry is referenced: 1) CPU traps to OS kernel, 2) OS verifies valid address in swap, 3) Finds a free frame (or evicts via LRU/Clock), 4) Issues disk I/O to read page, 5) Updates page table, 6) Restarts instruction. Thrashing happens when total working set sizes exceed physical RAM, causing the system to spend all CPU time swapping pages.",
    explanation: "The Working Set Model defines W(t, delta) as the set of pages referenced in the most recent delta time units. If sum of working set sizes > total physical frames, the OS must suspend a process to restore throughput.",
    category: "Operating Systems",
    topic: "Memory Management",
    difficulty: "Medium",
    company: "Microsoft",
    role: "Software Engineer",
    type: "technical",
    source: "Operating System Concepts (Silberschatz, Ch 9)",
    sourceUrl: "https://en.wikipedia.org/wiki/Page_fault",
  },
  {
    question: "Compare Mutex, Counting Semaphore, and Spinlock. When should a kernel or high-performance concurrent application choose a Spinlock over a Mutex?",
    answer: "A Mutex is a binary mutual exclusion lock with ownership semantics (only lock owner can unlock). A Semaphore is a signaling mechanism with an integer counter (wait/P decrements, signal/V increments). A Spinlock busy-waits in a CPU loop without sleeping or context switching. Use Spinlocks when the critical section is extremely brief (shorter than two thread context switches) and running on multi-core systems.",
    explanation: "Putting a thread to sleep involves saving registers, moving thread state to wait queue, invoking scheduler, and context switching (~1-2 microseconds). If the lock is held for mere nanoseconds, a spinlock is significantly faster.",
    category: "Operating Systems",
    topic: "Concurrency & Synchronization",
    difficulty: "Medium",
    company: "Uber",
    role: "Backend Engineer",
    type: "technical",
    source: "Operating System Concepts (Silberschatz, Ch 5)",
    sourceUrl: "https://en.wikipedia.org/wiki/Spinlock",
  },

  // ==========================================
  // DATABASE MANAGEMENT SYSTEMS (Ramakrishnan & Gehrke)
  // ==========================================
  {
    question: "Why do relational databases use B+ Trees instead of Binary Search Trees or Hash Indexes for table indexing?",
    answer: "1) High Fan-out: B+ Tree nodes match disk page sizes (4KB-16KB), holding hundreds of keys per node, keeping tree depth at 3-4 for millions of records (minimizing random disk I/Os). 2) Range Queries: B+ Trees link all leaf nodes in a doubly-linked list, allowing O(log N) lookup followed by fast sequential traversal. Hash indexes only support O(1) equality lookups and fail on range scans.",
    explanation: "Internal nodes store only keys and child pointers, maximizing key density per page. Leaf nodes store data records or row pointers. In contrast, BSTs have height O(log2 N) requiring 20-30 disk seeks per lookup.",
    category: "DBMS",
    topic: "B+ Tree Indexing",
    difficulty: "Hard",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "Database Management Systems (Ramakrishnan & Gehrke, Ch 10)",
    sourceUrl: "https://en.wikipedia.org/wiki/B%2B_tree",
  },
  {
    question: "Explain the four SQL isolation levels and the three concurrency read anomalies (Dirty Read, Non-repeatable Read, Phantom Read). How does MVCC resolve them without blocking reads?",
    answer: "Read Uncommitted (allows dirty reads). Read Committed (prevents dirty reads). Repeatable Read (prevents non-repeatable reads). Serializable (prevents all anomalies including phantoms). MVCC (Multi-Version Concurrency Control) maintains multiple row versions stamped with transaction IDs; readers view a consistent snapshot corresponding to transaction start timestamp, so reads never block writes and writes never block reads.",
    explanation: "Dirty Read: Reading uncommitted data of another txn that might rollback. Non-repeatable Read: Re-reading the same row within a transaction and seeing modified values. Phantom Read: Re-executing a range query and discovering new rows inserted by a committed concurrent txn.",
    category: "DBMS",
    topic: "Transactions & Concurrency",
    difficulty: "Hard",
    company: "Microsoft",
    role: "Software Engineer",
    type: "technical",
    source: "Database Management Systems (Ramakrishnan & Gehrke, Ch 16)",
    sourceUrl: "https://en.wikipedia.org/wiki/Isolation_(database_systems)",
  },
  {
    question: "Compare 3NF and BCNF. What is the exact mathematical definition of Boyce-Codd Normal Form, and when is a decomposition dependency-preserving?",
    answer: "A relation R is in BCNF if for every non-trivial functional dependency X -> Y, X is a superkey. 3NF is slightly more relaxed: for every X -> Y, X must be a superkey OR Y must be a prime attribute (part of some candidate key). Every BCNF relation is in 3NF, but BCNF decomposition may sometimes lose dependency preservation, whereas 3NF decomposition always preserves all dependencies and lossless join.",
    explanation: "Lossless-join test: R1 and R2 decomposition of R is lossless if R1 ∩ R2 -> R1 or R1 ∩ R2 -> R2 in F+. If an FD cannot be verified by checking single projected tables, inter-table joins are needed on every update, which is why practitioners often settle for 3NF.",
    category: "DBMS",
    topic: "Database Normalization",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "technical",
    source: "Database Management Systems (Ramakrishnan & Gehrke, Ch 19)",
    sourceUrl: "https://en.wikipedia.org/wiki/Boyce%E2%80%93Codd_normal_form",
  },

  // ==========================================
  // COMPUTER NETWORKING (Kurose & Ross)
  // ==========================================
  {
    question: "Describe the TCP 3-Way Handshake and 4-Way Teardown. Why does the TIME_WAIT state persist for 2 * MSL (Maximum Segment Lifetime)?",
    answer: "Handshake: Client sends SYN(seq=x) -> Server replies SYN-ACK(seq=y, ack=x+1) -> Client sends ACK(ack=y+1). Teardown: Client sends FIN -> Server sends ACK -> Server sends FIN -> Client sends ACK and enters TIME_WAIT. TIME_WAIT lasts 2 * MSL (typically 60-120s) to guarantee the final ACK reached the server (if lost, server retransmits FIN) and to prevent lingering duplicate packets from a previous connection from corrupting a new connection on the same socket pair.",
    explanation: "If client closed socket immediately without TIME_WAIT, and its final ACK was lost, server would stay in LAST_ACK state and reset any subsequent connection attempt on that port. MSL is standard engineering margin.",
    category: "Computer Networks",
    topic: "Transport Protocols",
    difficulty: "Medium",
    company: "Meta",
    role: "Software Engineer",
    type: "technical",
    source: "Computer Networking: A Top-Down Approach (Kurose & Ross, Ch 3)",
    sourceUrl: "https://en.wikipedia.org/wiki/Transmission_Control_Protocol",
  },
  {
    question: "Compare HTTP/1.1, HTTP/2, and HTTP/3. How does HTTP/3 over QUIC eliminate Head-of-Line (HoL) blocking?",
    answer: "HTTP/1.1 uses persistent TCP connections but suffers from application HoL blocking (requests queued serially on a connection). HTTP/2 introduces binary framing and multiplexed streams over a single TCP connection, eliminating application HoL blocking, but still suffers from TCP transport-level HoL blocking (a single lost TCP packet halts all multiplexed streams). HTTP/3 replaces TCP with QUIC over UDP, providing independent stream packet accounting: a lost packet in stream A never delays stream B.",
    explanation: "QUIC also merges the transport handshake with TLS 1.3 handshake, achieving 0-RTT or 1-RTT connection establishment, and supports connection migration across changing client IP addresses (e.g. WiFi to 5G cellular) via Connection IDs.",
    category: "Computer Networks",
    topic: "Application Protocols",
    difficulty: "Hard",
    company: "Google",
    role: "Software Engineer",
    type: "technical",
    source: "High Performance Browser Networking (Ilya Grigorik)",
    sourceUrl: "https://hpbn.co/",
  },

  // ==========================================
  // SYSTEM DESIGN & DISTRIBUTED SYSTEMS (Kleppmann DDIA)
  // ==========================================
  {
    question: "Explain the CAP Theorem and PACELC Theorem with real database examples (Cassandra vs DynamoDB vs PostgreSQL).",
    answer: "CAP: In an asynchronous network with Partitions (P), a distributed system can guarantee either Consistency (C - linearizability) or Availability (A - every non-failing node responds), but not both. PACELC extends CAP: If there is a Partition (P), choose Availability (A) or Consistency (C); Else (E), when network is operating normally, choose Latency (L) or Consistency (C). Example: Cassandra chooses PA/EL (Availability during partition, low latency normally via eventual consistency). Spanner/HBase chooses PC/EC (Consistency always).",
    explanation: "PACELC addresses normal operations where 99.9% of time there are no partitions, yet distributed databases must still trade replication latency against strict consistency.",
    category: "System Design",
    topic: "Distributed Systems",
    difficulty: "Hard",
    company: "Netflix",
    role: "Backend Engineer",
    type: "technical",
    source: "Designing Data-Intensive Applications (Martin Kleppmann, Ch 9)",
    sourceUrl: "https://en.wikipedia.org/wiki/PACELC_theorem",
  },
  {
    question: "Design a High-Throughput Distributed Rate Limiter (Token Bucket vs Leaky Bucket vs Sliding Window Counter). How do you handle race conditions in Redis?",
    answer: "Use the Sliding Window Counter algorithm or Token Bucket. Store timestamps in a Redis Sorted Set (ZADD) or atomic hash counter with Lua scripting. A Lua script executes atomically on the single Redis event loop, preventing race conditions between checking the count and incrementing it, avoiding distributed lock overhead.",
    explanation: "Lua script pattern: local current = redis.call('incr', key); if current == 1 then redis.call('expire', key, window) end; if current > limit then return 0 else return 1 end. For multi-datacenter setups, combine local in-memory token buckets with periodic asynchronous sync.",
    category: "System Design",
    topic: "Scalability & Rate Limiting",
    difficulty: "Hard",
    company: "Uber",
    role: "Backend Engineer",
    type: "technical",
    source: "System Design Interview (Alex Xu, Vol 1 Ch 4)",
    sourceUrl: "https://github.com/donnemartin/system-design-primer",
  },

  // ==========================================
  // AUTHENTIC BEHAVIORAL QUESTIONS (STAR FRAMEWORK)
  // ==========================================
  {
    question: "Amazon LP: Tell me about a time when you had to make an important architectural decision with incomplete data (Bias for Action & Calculated Risk).",
    category: "Behavioral",
    topic: "Bias for Action",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "behavioral",
    source: "Amazon Leadership Principles",
    sourceUrl: "https://www.amazon.jobs/content/en/our-workplace/leadership-principles",
    starResponse: {
      situation: "Two weeks before launching our student transcript ingestion service, our team noticed memory spikes during PDF OCR parsing with no vendor support response.",
      task: "I had to decide whether to delay the university campus pilot launch or implement a fallback pipeline with incomplete benchmarks.",
      action: "I recognized this was a two-way door decision. I designed a circuit breaker that offloaded heavy PDFs to a background worker queue with timeout caps and fallback local regex heuristics.",
      result: "We launched on schedule. The worker queue absorbed 94% of sudden load spikes with zero server crashes, processing 14,000 pages during orientation week.",
    },
  },
  {
    question: "Googleyness: Tell me about a time when you strongly disagreed with a senior teammate's technical proposal and how you handled the disagreement.",
    category: "Behavioral",
    topic: "Disagree and Commit & Intellectual Humility",
    difficulty: "Medium",
    company: "Google",
    role: "Software Engineer",
    type: "behavioral",
    source: "Google Hiring Guidelines",
    sourceUrl: "https://careers.google.com/how-we-hire/",
    starResponse: {
      situation: "A senior engineer proposed replacing our relational PostgreSQL schema with a single NoSQL document store to speed up initial feature prototyping.",
      task: "I needed to voice serious long-term consistency and financial transaction concerns without creating team friction.",
      action: "Instead of debating theoretically, I created a side-by-side technical evaluation matrix comparing multi-table joins, ACID guarantees, and projected read/write patterns for our reporting features.",
      result: "The team agreed PostgreSQL with JSONB columns gave us schema flexibility while preserving relational integrity. The senior engineer complimented the data-driven evaluation.",
    },
  },
  {
    question: "Failure & Accountability: Tell me about a time when a project or feature you were responsible for failed or caused an outage. What was your retrospective?",
    category: "Behavioral",
    topic: "Failure & Accountability",
    difficulty: "Hard",
    company: "Meta",
    role: "Software Engineer",
    type: "behavioral",
    source: "Harvard Technical Interview Guide",
    sourceUrl: "https://careers.google.com/how-we-hire/",
    starResponse: {
      situation: "I merged a database index migration directly to production on a table with 2 million active user sessions during daytime traffic.",
      task: "The table lock caused request timeouts for 7 minutes, triggering customer support alerts.",
      action: "I killed the hanging DDL transaction immediately, restored active traffic, wrote a blameless post-mortem, and implemented CREATE INDEX CONCURRENTLY guidelines with automated CI linters.",
      result: "The team adopted our new zero-downtime migration runbook, and no production locking outages occurred over the following academic year.",
    },
  },

  // ==========================================
  // BLIND 75 & TOP INTERVIEW 150 CODING PROBLEMS
  // ==========================================
  {
    question: "3Sum — Find all unique triplets in array that sum to zero",
    category: "Algorithms",
    topic: "Two Pointers",
    difficulty: "Medium",
    company: "Meta",
    role: "Software Engineer",
    type: "coding",
    source: "LeetCode 15 / Blind 75",
    sourceUrl: "https://leetcode.com/problems/3sum/",
    problemUrl: "https://leetcode.com/problems/3sum/",
    answer: "Sort the array in O(N log N). Fix the first element nums[i] in an outer loop. Use two pointers (left = i+1, right = n-1) to find pairs that sum to -nums[i]. Skip duplicate elements at every pointer to avoid duplicate triplets.",
    explanation: "Time complexity is O(N^2), Space complexity is O(log N) to O(N) depending on sorting implementation. Avoiding duplicates requires skipping consecutive identical values for both i, left, and right.",
  },
  {
    question: "Container With Most Water — Maximum water area between two vertical lines",
    category: "Algorithms",
    topic: "Two Pointers",
    difficulty: "Medium",
    company: "Google",
    role: "Software Engineer",
    type: "coding",
    source: "LeetCode 11 / Blind 75",
    sourceUrl: "https://leetcode.com/problems/container-with-most-water/",
    problemUrl: "https://leetcode.com/problems/container-with-most-water/",
    answer: "Initialize left=0 and right=n-1. Calculate area = min(height[left], height[right]) * (right - left). Move the pointer pointing to the shorter line inward. Repeat until left meets right.",
    explanation: "Time complexity: O(N), Space complexity: O(1). Proof of correctness: Moving the taller line can never increase the area because width decreases and height remains bounded by the shorter line.",
  },
  {
    question: "Merge Intervals — Merge all overlapping intervals",
    category: "Algorithms",
    topic: "Intervals & Sorting",
    difficulty: "Medium",
    company: "Amazon",
    role: "Software Engineer",
    type: "coding",
    source: "LeetCode 56 / Blind 75",
    sourceUrl: "https://leetcode.com/problems/merge-intervals/",
    problemUrl: "https://leetcode.com/problems/merge-intervals/",
    answer: "Sort intervals by start time. Iterate through sorted intervals: if current interval's start <= previous interval's end, merge them by setting prev.end = max(prev.end, curr.end); otherwise append current interval.",
    explanation: "Time complexity: O(N log N) for sorting, O(N) for linear pass. Space complexity: O(N) for result output.",
  },
  {
    question: "Coin Change — Minimum coins to make up an amount",
    category: "Algorithms",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    company: "Microsoft",
    role: "Software Engineer",
    type: "coding",
    source: "LeetCode 322 / Blind 75",
    sourceUrl: "https://leetcode.com/problems/coin-change/",
    problemUrl: "https://leetcode.com/problems/coin-change/",
    answer: "Bottom-up 1D DP: dp[i] = min(dp[i], dp[i - coin] + 1) for each coin <= i. Initialize dp array with amount + 1. If dp[amount] > amount, return -1.",
    explanation: "Time complexity: O(amount * coins.length), Space complexity: O(amount). Greedy algorithms (e.g. taking largest coin) fail for arbitrary coin denominations.",
  },
  {
    question: "Trapping Rain Water — Compute trapped rainwater after raining",
    category: "Algorithms",
    topic: "Two Pointers / Monotonic Stack",
    difficulty: "Hard",
    company: "Google",
    role: "Software Engineer",
    type: "coding",
    source: "LeetCode 42 / Hard Classics",
    sourceUrl: "https://leetcode.com/problems/trapping-rain-water/",
    problemUrl: "https://leetcode.com/problems/trapping-rain-water/",
    answer: "Use two pointers left=0, right=n-1 with leftMax and rightMax tracking variables. If height[left] < height[right], process left (accumulate water = max(0, leftMax - height[left])), else process right.",
    explanation: "Time complexity: O(N), Space complexity: O(1). Eliminates the need for O(N) auxiliary prefix/suffix max arrays.",
  }
];

module.exports = {
  VETTED_INTERVIEW_QUESTIONS,
};
